# Generated by Django 4.2.7 on 2025-10-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Unique identifier for conversation session', max_length=100)),
                ('user_message', models.TextField(help_text="User's input message")),
                ('bot_response', models.TextField(help_text="AI model's response")),
                ('context_summary', models.TextField(blank=True, help_text='Optional summary of conversation context', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Record',
                'verbose_name_plural': 'Chat Records',
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
