# Generated by Django 4.2.7 on 2025-10-21 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0003_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('file', models.FileField(help_text='Uploaded file', upload_to='documents/')),
                ('file_type', models.CharField(help_text='File type (pdf, docx, txt, etc.)', max_length=50)),
                ('extracted_text', models.TextField(help_text='Extracted text content from the document')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-upload_date'],
            },
        ),
    ]
